services:
  ticketa:
    container_name: ticketa
    image: ticketa:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      PG_PORT: ${PG_PORT}
      PG_HOST: database
      SERVER_PORT: 8080
      LOG_LEVEL: ${LOG_LEVEL:-info}
    volumes:
      - ./config/ticketa.yaml:/config/ticketa.yaml:ro
    depends_on:
      database:
        condition: service_healthy
    networks:
      - ticketa-web
      - ticketa-db

  database:
    container_name: ticketa-database
    image: "postgres:18.4"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ticketa_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ticketa-db

networks:
  ticketa-web: {}
  ticketa-db:
    internal: true

volumes:
  ticketa_postgres_data:
