// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_log.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const countActivityLog = `-- name: CountActivityLog :one
SELECT COUNT(*) FROM activity_log
WHERE
    ($1::VARCHAR IS NULL  OR event_type  = $1)
    AND ($2::INTEGER IS NULL OR actor_id    = $2)
    AND ($3::VARCHAR IS NULL OR target_type = $3)
    AND ($4::BIGINT IS NULL OR target_id   = $4)
    AND ($5::TIMESTAMPTZ IS NULL OR created_at >= $5)
    AND ($6::TIMESTAMPTZ IS NULL   OR created_at <= $6)
`

type CountActivityLogParams struct {
	EventType  sql.NullString
	ActorID    sql.NullInt32
	TargetType sql.NullString
	TargetID   sql.NullInt64
	FromTs     sql.NullTime
	ToTs       sql.NullTime
}

func (q *Queries) CountActivityLog(ctx context.Context, arg CountActivityLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityLog,
		arg.EventType,
		arg.ActorID,
		arg.TargetType,
		arg.TargetID,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivityLogForUser = `-- name: CountActivityLogForUser :one
SELECT COUNT(*) FROM activity_log
WHERE (
        actor_id = $1::INTEGER
        OR (target_type = 'ticket' AND target_id IN (
              SELECT id FROM tickets WHERE author_id = $1::INTEGER
            ))
      )
    AND ($2::VARCHAR IS NULL  OR event_type  = $2)
    AND ($3::VARCHAR IS NULL OR target_type = $3)
    AND ($4::BIGINT IS NULL OR target_id   = $4)
    AND ($5::TIMESTAMPTZ IS NULL OR created_at >= $5)
    AND ($6::TIMESTAMPTZ IS NULL   OR created_at <= $6)
`

type CountActivityLogForUserParams struct {
	ActorID    int32
	EventType  sql.NullString
	TargetType sql.NullString
	TargetID   sql.NullInt64
	FromTs     sql.NullTime
	ToTs       sql.NullTime
}

func (q *Queries) CountActivityLogForUser(ctx context.Context, arg CountActivityLogForUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityLogForUser,
		arg.ActorID,
		arg.EventType,
		arg.TargetType,
		arg.TargetID,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO activity_log (event_type, actor_id, target_type, target_id, payload)
VALUES ($1, $2, $3, $4, $5)
`

type CreateActivityLogParams struct {
	EventType  string
	ActorID    sql.NullInt32
	TargetType sql.NullString
	TargetID   sql.NullInt64
	Payload    pqtype.NullRawMessage
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.ExecContext(ctx, createActivityLog,
		arg.EventType,
		arg.ActorID,
		arg.TargetType,
		arg.TargetID,
		arg.Payload,
	)
	return err
}

const listActivityLog = `-- name: ListActivityLog :many
SELECT id, event_type, actor_id, target_type, target_id, payload, created_at
FROM activity_log
WHERE
    ($1::VARCHAR IS NULL  OR event_type  = $1)
    AND ($2::INTEGER IS NULL OR actor_id    = $2)
    AND ($3::VARCHAR IS NULL OR target_type = $3)
    AND ($4::BIGINT IS NULL OR target_id   = $4)
    AND ($5::TIMESTAMPTZ IS NULL OR created_at >= $5)
    AND ($6::TIMESTAMPTZ IS NULL   OR created_at <= $6)
ORDER BY created_at DESC
LIMIT  $8::INTEGER
OFFSET $7::INTEGER
`

type ListActivityLogParams struct {
	EventType  sql.NullString
	ActorID    sql.NullInt32
	TargetType sql.NullString
	TargetID   sql.NullInt64
	FromTs     sql.NullTime
	ToTs       sql.NullTime
	Off        int32
	Lim        int32
}

func (q *Queries) ListActivityLog(ctx context.Context, arg ListActivityLogParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLog,
		arg.EventType,
		arg.ActorID,
		arg.TargetType,
		arg.TargetID,
		arg.FromTs,
		arg.ToTs,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorID,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogForUser = `-- name: ListActivityLogForUser :many
SELECT id, event_type, actor_id, target_type, target_id, payload, created_at
FROM activity_log
WHERE (
        actor_id = $1::INTEGER
        OR (target_type = 'ticket' AND target_id IN (
              SELECT id FROM tickets WHERE author_id = $1::INTEGER
            ))
      )
    AND ($2::VARCHAR IS NULL  OR event_type  = $2)
    AND ($3::VARCHAR IS NULL OR target_type = $3)
    AND ($4::BIGINT IS NULL OR target_id   = $4)
    AND ($5::TIMESTAMPTZ IS NULL OR created_at >= $5)
    AND ($6::TIMESTAMPTZ IS NULL   OR created_at <= $6)
ORDER BY created_at DESC
LIMIT  $8::INTEGER
OFFSET $7::INTEGER
`

type ListActivityLogForUserParams struct {
	ActorID    int32
	EventType  sql.NullString
	TargetType sql.NullString
	TargetID   sql.NullInt64
	FromTs     sql.NullTime
	ToTs       sql.NullTime
	Off        int32
	Lim        int32
}

// Zahrnuje vlastní akce uživatele a dále akce ostatních na tiketech, jejichž
// je uživatel autorem (např. když štáb změní stav mého tiketu). Stejné
// volitelné filtry jako ListActivityLog, navíc k povinnému actor_id.
func (q *Queries) ListActivityLogForUser(ctx context.Context, arg ListActivityLogForUserParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLogForUser,
		arg.ActorID,
		arg.EventType,
		arg.TargetType,
		arg.TargetID,
		arg.FromTs,
		arg.ToTs,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorID,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
