// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (email, invited_by, token, user_type, expires_at)
VALUES ($1, $2, $3, $4, NOW() + INTERVAL '7 days')
RETURNING id, email, invited_by, token, user_type, created_at, expires_at, used_at
`

type CreateInvitationParams struct {
	Email     string
	InvitedBy int32
	Token     string
	UserType  UserType
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, createInvitation,
		arg.Email,
		arg.InvitedBy,
		arg.Token,
		arg.UserType,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InvitedBy,
		&i.Token,
		&i.UserType,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, email, invited_by, token, user_type, created_at, expires_at, used_at
FROM invitations
WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InvitedBy,
		&i.Token,
		&i.UserType,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markInvitationUsed = `-- name: MarkInvitationUsed :exec
UPDATE invitations SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkInvitationUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markInvitationUsed, id)
	return err
}
