// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuthProvider string

const (
	AuthProviderLocal AuthProvider = "local"
	AuthProviderLdap  AuthProvider = "ldap"
	AuthProviderAd    AuthProvider = "ad"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider
	Valid        bool // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type UserType string

const (
	UserTypeStudent    UserType = "student"
	UserTypeStaff      UserType = "staff"
	UserTypeMaintainer UserType = "maintainer"
)

func (e *UserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserType(s)
	case string:
		*e = UserType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserType: %T", src)
	}
	return nil
}

type NullUserType struct {
	UserType UserType
	Valid    bool // Valid is true if UserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserType) Scan(value interface{}) error {
	if value == nil {
		ns.UserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserType), nil
}

type LdapLogin struct {
	ID                int32
	DistinguishedName string
	Uid               sql.NullString
	SamAccountName    sql.NullString
	Upn               sql.NullString
	ObjectGuid        uuid.NullUUID
	ObjectSid         sql.NullString
	LdapServer        string
	BaseDn            string
	LastSyncedAt      sql.NullTime
}

type LocalLogin struct {
	ID           int32
	PasswordHash string
	MustChangePw bool
	PwChangedAt  sql.NullTime
}

type MaintainerProfile struct {
	ID           int32
	AccessLevel  int16
	ManagedScope sql.NullString
}

type Session struct {
	ID         int64
	UserID     int64
	Token      string
	Ip         pqtype.Inet
	UserAgent  string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
	Deleted    bool
}

type StaffProfile struct {
	ID            int32
	EmployeeID    string
	Department    sql.NullString
	JobTitle      sql.NullString
	IsTeacher     bool
	EmployedSince sql.NullTime
}

type StudentProfile struct {
	ID           int32
	StudentID    string
	EnrolledAt   time.Time
	GraduationAt sql.NullTime
	ClassGroup   sql.NullString
}

type Ticket struct {
	ID        int64
	Title     string
	Body      string
	CreatedAt time.Time
	AuthorID  int32
	StatusID  sql.NullInt32
}

type TicketStatus struct {
	ID       int32
	Title    string
	Color    string
	Position int32
}

type User struct {
	ID          int32
	Email       string
	FirstName   sql.NullString
	LastName    sql.NullString
	UserType    UserType
	Provider    AuthProvider
	IsActive    bool
	CreatedAt   time.Time
	LastLoginAt sql.NullTime
}
