// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::BIGINT
FROM notifications
WHERE user_id = $1 AND is_viewed = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, text, ticket_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, type, text, ticket_id, is_viewed, created_at
`

type CreateNotificationParams struct {
	UserID   int32
	Type     string
	Text     string
	TicketID sql.NullInt64
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Text,
		arg.TicketID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Text,
		&i.TicketID,
		&i.IsViewed,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationsForUser = `-- name: GetNotificationsForUser :many
SELECT id, user_id, type, text, ticket_id, is_viewed, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) GetNotificationsForUser(ctx context.Context, userID int32) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Text,
			&i.TicketID,
			&i.IsViewed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsViewed = `-- name: MarkAllNotificationsViewed :exec
UPDATE notifications
SET is_viewed = TRUE
WHERE user_id = $1 AND is_viewed = FALSE
`

func (q *Queries) MarkAllNotificationsViewed(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsViewed, userID)
	return err
}
