// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_preferences.sql

package db

import (
	"context"
	"database/sql"
)

const deleteEmailOptOut = `-- name: DeleteEmailOptOut :exec
DELETE FROM notification_email_optouts WHERE user_id = $1 AND type = $2
`

type DeleteEmailOptOutParams struct {
	UserID int32
	Type   string
}

func (q *Queries) DeleteEmailOptOut(ctx context.Context, arg DeleteEmailOptOutParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmailOptOut, arg.UserID, arg.Type)
	return err
}

const getAllActiveStaff = `-- name: GetAllActiveStaff :many
SELECT id, email, first_name, last_name FROM users
WHERE user_type IN ('staff', 'maintainer', 'admin') AND is_active = TRUE
`

type GetAllActiveStaffRow struct {
	ID        int32
	Email     string
	FirstName sql.NullString
	LastName  sql.NullString
}

func (q *Queries) GetAllActiveStaff(ctx context.Context) ([]GetAllActiveStaffRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveStaff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveStaffRow
	for rows.Next() {
		var i GetAllActiveStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailOptOuts = `-- name: GetEmailOptOuts :many
SELECT type FROM notification_email_optouts WHERE user_id = $1
`

func (q *Queries) GetEmailOptOuts(ctx context.Context, userID int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEmailOptOuts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmailOptOut = `-- name: UpsertEmailOptOut :exec
INSERT INTO notification_email_optouts (user_id, type)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type UpsertEmailOptOutParams struct {
	UserID int32
	Type   string
}

func (q *Queries) UpsertEmailOptOut(ctx context.Context, arg UpsertEmailOptOutParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmailOptOut, arg.UserID, arg.Type)
	return err
}
