// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_settings.sql

package db

import (
	"context"
)

const getAllServerSettings = `-- name: GetAllServerSettings :many
SELECT key, value, from_env, updated_at
FROM server_settings
ORDER BY key
`

func (q *Queries) GetAllServerSettings(ctx context.Context) ([]ServerSetting, error) {
	rows, err := q.db.QueryContext(ctx, getAllServerSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServerSetting
	for rows.Next() {
		var i ServerSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.FromEnv,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerSetting = `-- name: GetServerSetting :one
SELECT key, value, from_env, updated_at
FROM server_settings
WHERE key = $1
`

func (q *Queries) GetServerSetting(ctx context.Context, key string) (ServerSetting, error) {
	row := q.db.QueryRowContext(ctx, getServerSetting, key)
	var i ServerSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.FromEnv,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertServerSetting = `-- name: UpsertServerSetting :exec
INSERT INTO server_settings (key, value, from_env, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (key) DO UPDATE
    SET value      = EXCLUDED.value,
        from_env   = EXCLUDED.from_env,
        updated_at = NOW()
`

type UpsertServerSettingParams struct {
	Key     string
	Value   string
	FromEnv bool
}

func (q *Queries) UpsertServerSetting(ctx context.Context, arg UpsertServerSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertServerSetting, arg.Key, arg.Value, arg.FromEnv)
	return err
}
