// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/sqlc-dev/pqtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token, ip, user_agent, expires_at)
VALUES ($1, $2, $3, $4, NOW() + $5::interval)
RETURNING id, user_id, token, ip, user_agent, created_at, expires_at, last_seen_at, deleted
`

type CreateSessionParams struct {
	UserID    int64
	Token     string
	Ip        pqtype.Inet
	UserAgent string
	Column5   int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.Token,
		arg.Ip,
		arg.UserAgent,
		arg.Column5,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.Deleted,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
UPDATE sessions
SET    last_seen_at = NOW()
WHERE  token      = $1
  AND  deleted    = FALSE
  AND  expires_at > NOW()
RETURNING id, user_id, token, ip, user_agent, created_at, expires_at, last_seen_at, deleted
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.Deleted,
	)
	return i, err
}

const getSessionByUserID = `-- name: GetSessionByUserID :one
SELECT id, user_id, token, ip, user_agent, created_at, expires_at, last_seen_at, deleted FROM sessions
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetSessionByUserID(ctx context.Context, userID int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUserID, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.Deleted,
	)
	return i, err
}

const regenerateToken = `-- name: RegenerateToken :one
UPDATE sessions
SET    token        = $2,
       ip           = $3,
       user_agent   = $4,
       expires_at   = NOW() + $5::interval,
       last_seen_at = NOW(),
       deleted      = FALSE
WHERE  user_id = $1
RETURNING id, user_id, token, ip, user_agent, created_at, expires_at, last_seen_at, deleted
`

type RegenerateTokenParams struct {
	UserID    int64
	Token     string
	Ip        pqtype.Inet
	UserAgent string
	Column5   int64
}

func (q *Queries) RegenerateToken(ctx context.Context, arg RegenerateTokenParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, regenerateToken,
		arg.UserID,
		arg.Token,
		arg.Ip,
		arg.UserAgent,
		arg.Column5,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.Deleted,
	)
	return i, err
}

const softDeleteSession = `-- name: SoftDeleteSession :exec
UPDATE sessions
SET    deleted    = TRUE,
       token      = '',
       expires_at = NOW()
WHERE  token   = $1
  AND  deleted = FALSE
`

func (q *Queries) SoftDeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, softDeleteSession, token)
	return err
}

const softDeleteSessionByUserID = `-- name: SoftDeleteSessionByUserID :exec
UPDATE sessions
SET    deleted    = TRUE,
       token      = '',
       expires_at = NOW()
WHERE  user_id = $1
  AND  deleted = FALSE
`

func (q *Queries) SoftDeleteSessionByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteSessionByUserID, userID)
	return err
}
