// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const approveTicketPriority = `-- name: ApproveTicketPriority :one
UPDATE tickets
SET priority             = requested_priority,
    priority_approved_by = $1::INTEGER,
    requested_priority   = NULL
WHERE id = $2 AND requested_priority IS NOT NULL
RETURNING id, title, body, created_at, author_id, status_id, priority, assigned_to, location, category, updated_at, requested_priority, priority_approved_by
`

type ApproveTicketPriorityParams struct {
	ApprovedBy int32
	ID         int64
}

func (q *Queries) ApproveTicketPriority(ctx context.Context, arg ApproveTicketPriorityParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, approveTicketPriority, arg.ApprovedBy, arg.ID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorID,
		&i.StatusID,
		&i.Priority,
		&i.AssignedTo,
		&i.Location,
		&i.Category,
		&i.UpdatedAt,
		&i.RequestedPriority,
		&i.PriorityApprovedBy,
	)
	return i, err
}

const countTicketsFiltered = `-- name: CountTicketsFiltered :one
SELECT COUNT(*)::BIGINT
FROM tickets t
WHERE
    ($1::INTEGER IS NULL    OR t.status_id   = $1)
    AND ($2::VARCHAR IS NULL  OR t.priority    = $2)
    AND ($3::INTEGER IS NULL OR t.assigned_to = $3)
    AND ($4::INTEGER IS NULL OR t.author_id   = $4)
    AND ($5::VARCHAR IS NULL  OR t.category    = $5)
    AND ($6::BOOLEAN IS NULL OR (t.requested_priority IS NOT NULL) = $6)
    AND (
        $7::TEXT = ''
        OR t.title ILIKE '%' || $7 || '%'
        OR t.body  ILIKE '%' || $7 || '%'
    )
`

type CountTicketsFilteredParams struct {
	StatusID                sql.NullInt32
	Priority                sql.NullString
	AssignedTo              sql.NullInt32
	AuthorID                sql.NullInt32
	Category                sql.NullString
	PendingPriorityApproval sql.NullBool
	Q                       string
}

func (q *Queries) CountTicketsFiltered(ctx context.Context, arg CountTicketsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTicketsFiltered,
		arg.StatusID,
		arg.Priority,
		arg.AssignedTo,
		arg.AuthorID,
		arg.Category,
		arg.PendingPriorityApproval,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (title, body, author_id, status_id, priority, location, category, assigned_to, requested_priority)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, body, created_at, author_id, status_id, priority, assigned_to, location, category, updated_at, requested_priority, priority_approved_by
`

type CreateTicketParams struct {
	Title             string
	Body              string
	AuthorID          int32
	StatusID          sql.NullInt32
	Priority          string
	Location          string
	Category          string
	AssignedTo        sql.NullInt32
	RequestedPriority sql.NullString
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, createTicket,
		arg.Title,
		arg.Body,
		arg.AuthorID,
		arg.StatusID,
		arg.Priority,
		arg.Location,
		arg.Category,
		arg.AssignedTo,
		arg.RequestedPriority,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorID,
		&i.StatusID,
		&i.Priority,
		&i.AssignedTo,
		&i.Location,
		&i.Category,
		&i.UpdatedAt,
		&i.RequestedPriority,
		&i.PriorityApprovedBy,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets
WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTicket, id)
	return err
}

const getStatusTitle = `-- name: GetStatusTitle :one
SELECT title FROM ticket_statuses WHERE id = $1
`

func (q *Queries) GetStatusTitle(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getStatusTitle, id)
	var title string
	err := row.Scan(&title)
	return title, err
}

const getTicket = `-- name: GetTicket :one
SELECT
    t.id, t.title, t.body, t.created_at, t.author_id, t.status_id, t.priority, t.assigned_to, t.location, t.category, t.updated_at, t.requested_priority, t.priority_approved_by,
    COALESCE(u.first_name || ' ' || u.last_name, u.email)     AS author_name,
    COALESCE(a.first_name || ' ' || a.last_name, a.email, '') AS assignee_name,
    (SELECT COUNT(*)::INT FROM ticket_votes tv WHERE tv.ticket_id = t.id) AS vote_count,
    EXISTS(
        SELECT 1 FROM ticket_votes tv
        WHERE tv.ticket_id = t.id AND tv.user_id = $1::INTEGER
    ) AS user_has_voted
FROM tickets t
JOIN  users u ON u.id = t.author_id
LEFT JOIN users a ON a.id = t.assigned_to
WHERE t.id = $2::BIGINT
`

type GetTicketParams struct {
	CurrentUserID int32
	ID            int64
}

type GetTicketRow struct {
	ID                 int64
	Title              string
	Body               string
	CreatedAt          time.Time
	AuthorID           int32
	StatusID           sql.NullInt32
	Priority           string
	AssignedTo         sql.NullInt32
	Location           string
	Category           string
	UpdatedAt          time.Time
	RequestedPriority  sql.NullString
	PriorityApprovedBy sql.NullInt32
	AuthorName         string
	AssigneeName       string
	VoteCount          int32
	UserHasVoted       bool
}

func (q *Queries) GetTicket(ctx context.Context, arg GetTicketParams) (GetTicketRow, error) {
	row := q.db.QueryRowContext(ctx, getTicket, arg.CurrentUserID, arg.ID)
	var i GetTicketRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorID,
		&i.StatusID,
		&i.Priority,
		&i.AssignedTo,
		&i.Location,
		&i.Category,
		&i.UpdatedAt,
		&i.RequestedPriority,
		&i.PriorityApprovedBy,
		&i.AuthorName,
		&i.AssigneeName,
		&i.VoteCount,
		&i.UserHasVoted,
	)
	return i, err
}

const insertTicketHistory = `-- name: InsertTicketHistory :exec
INSERT INTO ticket_history (ticket_id, actor_id, actor_name, event, old_val, new_val)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTicketHistoryParams struct {
	TicketID  int64
	ActorID   int32
	ActorName string
	Event     string
	OldVal    sql.NullString
	NewVal    sql.NullString
}

func (q *Queries) InsertTicketHistory(ctx context.Context, arg InsertTicketHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketHistory,
		arg.TicketID,
		arg.ActorID,
		arg.ActorName,
		arg.Event,
		arg.OldVal,
		arg.NewVal,
	)
	return err
}

const listTicketHistory = `-- name: ListTicketHistory :many
SELECT id, ticket_id, actor_id, actor_name, event, old_val, new_val, created_at
FROM ticket_history
WHERE ticket_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTicketHistory(ctx context.Context, ticketID int64) ([]TicketHistory, error) {
	rows, err := q.db.QueryContext(ctx, listTicketHistory, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketHistory
	for rows.Next() {
		var i TicketHistory
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.ActorID,
			&i.ActorName,
			&i.Event,
			&i.OldVal,
			&i.NewVal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsFiltered = `-- name: ListTicketsFiltered :many
SELECT
    t.id, t.title, t.body, t.created_at, t.author_id, t.status_id, t.priority, t.assigned_to, t.location, t.category, t.updated_at, t.requested_priority, t.priority_approved_by,
    COALESCE(u.first_name || ' ' || u.last_name, u.email)     AS author_name,
    COALESCE(a.first_name || ' ' || a.last_name, a.email, '') AS assignee_name,
    (SELECT COUNT(*)::INT FROM ticket_votes tv WHERE tv.ticket_id = t.id) AS vote_count,
    EXISTS(
        SELECT 1 FROM ticket_votes tv
        WHERE tv.ticket_id = t.id AND tv.user_id = $1::INTEGER
    ) AS user_has_voted
FROM tickets t
JOIN  users u ON u.id = t.author_id
LEFT JOIN users a ON a.id = t.assigned_to
WHERE
    ($2::INTEGER IS NULL    OR t.status_id   = $2)
    AND ($3::VARCHAR IS NULL  OR t.priority    = $3)
    AND ($4::INTEGER IS NULL OR t.assigned_to = $4)
    AND ($5::INTEGER IS NULL OR t.author_id   = $5)
    AND ($6::VARCHAR IS NULL  OR t.category    = $6)
    AND ($7::BOOLEAN IS NULL OR (t.requested_priority IS NOT NULL) = $7)
    AND (
        $8::TEXT = ''
        OR t.title ILIKE '%' || $8 || '%'
        OR t.body  ILIKE '%' || $8 || '%'
    )
ORDER BY t.created_at DESC
LIMIT  $10::INTEGER
OFFSET $9::INTEGER
`

type ListTicketsFilteredParams struct {
	CurrentUserID           int32
	StatusID                sql.NullInt32
	Priority                sql.NullString
	AssignedTo              sql.NullInt32
	AuthorID                sql.NullInt32
	Category                sql.NullString
	PendingPriorityApproval sql.NullBool
	Q                       string
	Off                     int32
	Lim                     int32
}

type ListTicketsFilteredRow struct {
	ID                 int64
	Title              string
	Body               string
	CreatedAt          time.Time
	AuthorID           int32
	StatusID           sql.NullInt32
	Priority           string
	AssignedTo         sql.NullInt32
	Location           string
	Category           string
	UpdatedAt          time.Time
	RequestedPriority  sql.NullString
	PriorityApprovedBy sql.NullInt32
	AuthorName         string
	AssigneeName       string
	VoteCount          int32
	UserHasVoted       bool
}

func (q *Queries) ListTicketsFiltered(ctx context.Context, arg ListTicketsFilteredParams) ([]ListTicketsFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsFiltered,
		arg.CurrentUserID,
		arg.StatusID,
		arg.Priority,
		arg.AssignedTo,
		arg.AuthorID,
		arg.Category,
		arg.PendingPriorityApproval,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsFilteredRow
	for rows.Next() {
		var i ListTicketsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorID,
			&i.StatusID,
			&i.Priority,
			&i.AssignedTo,
			&i.Location,
			&i.Category,
			&i.UpdatedAt,
			&i.RequestedPriority,
			&i.PriorityApprovedBy,
			&i.AuthorName,
			&i.AssigneeName,
			&i.VoteCount,
			&i.UserHasVoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectTicketPriority = `-- name: RejectTicketPriority :one
UPDATE tickets
SET requested_priority = NULL
WHERE id = $1 AND requested_priority IS NOT NULL
RETURNING id, title, body, created_at, author_id, status_id, priority, assigned_to, location, category, updated_at, requested_priority, priority_approved_by
`

func (q *Queries) RejectTicketPriority(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, rejectTicketPriority, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorID,
		&i.StatusID,
		&i.Priority,
		&i.AssignedTo,
		&i.Location,
		&i.Category,
		&i.UpdatedAt,
		&i.RequestedPriority,
		&i.PriorityApprovedBy,
	)
	return i, err
}

const unvoteTicket = `-- name: UnvoteTicket :exec
DELETE FROM ticket_votes WHERE ticket_id = $1 AND user_id = $2
`

type UnvoteTicketParams struct {
	TicketID int64
	UserID   int32
}

func (q *Queries) UnvoteTicket(ctx context.Context, arg UnvoteTicketParams) error {
	_, err := q.db.ExecContext(ctx, unvoteTicket, arg.TicketID, arg.UserID)
	return err
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET title               = COALESCE($1,    title),
    body                = COALESCE($2,     body),
    priority            = COALESCE($3, priority),
    location            = COALESCE($4, location),
    category            = COALESCE($5, category),
    status_id           = $6,
    requested_priority  = COALESCE($7, requested_priority)
WHERE id = $8
RETURNING id, title, body, created_at, author_id, status_id, priority, assigned_to, location, category, updated_at, requested_priority, priority_approved_by
`

type UpdateTicketParams struct {
	Title             sql.NullString
	Body              sql.NullString
	Priority          sql.NullString
	Location          sql.NullString
	Category          sql.NullString
	StatusID          sql.NullInt32
	RequestedPriority sql.NullString
	ID                int64
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, updateTicket,
		arg.Title,
		arg.Body,
		arg.Priority,
		arg.Location,
		arg.Category,
		arg.StatusID,
		arg.RequestedPriority,
		arg.ID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorID,
		&i.StatusID,
		&i.Priority,
		&i.AssignedTo,
		&i.Location,
		&i.Category,
		&i.UpdatedAt,
		&i.RequestedPriority,
		&i.PriorityApprovedBy,
	)
	return i, err
}

const updateTicketMeta = `-- name: UpdateTicketMeta :one
UPDATE tickets
SET assigned_to = $1,
    status_id   = $2,
    priority    = COALESCE($3, priority),
    location    = COALESCE($4, location),
    category    = COALESCE($5, category)
WHERE id = $6
RETURNING id, title, body, created_at, author_id, status_id, priority, assigned_to, location, category, updated_at, requested_priority, priority_approved_by
`

type UpdateTicketMetaParams struct {
	AssignedTo sql.NullInt32
	StatusID   sql.NullInt32
	Priority   sql.NullString
	Location   sql.NullString
	Category   sql.NullString
	ID         int64
}

func (q *Queries) UpdateTicketMeta(ctx context.Context, arg UpdateTicketMetaParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, updateTicketMeta,
		arg.AssignedTo,
		arg.StatusID,
		arg.Priority,
		arg.Location,
		arg.Category,
		arg.ID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorID,
		&i.StatusID,
		&i.Priority,
		&i.AssignedTo,
		&i.Location,
		&i.Category,
		&i.UpdatedAt,
		&i.RequestedPriority,
		&i.PriorityApprovedBy,
	)
	return i, err
}

const voteTicket = `-- name: VoteTicket :exec
INSERT INTO ticket_votes (ticket_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type VoteTicketParams struct {
	TicketID int64
	UserID   int32
}

func (q *Queries) VoteTicket(ctx context.Context, arg VoteTicketParams) error {
	_, err := q.db.ExecContext(ctx, voteTicket, arg.TicketID, arg.UserID)
	return err
}
