// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_statuses.sql

package db

import (
	"context"
)

const createTicketStatus = `-- name: CreateTicketStatus :one
INSERT INTO ticket_statuses (title, color, position, is_closed)
VALUES ($1, $2, $3, $4)
RETURNING id, title, color, position, is_closed
`

type CreateTicketStatusParams struct {
	Title    string
	Color    string
	Position int32
	IsClosed bool
}

func (q *Queries) CreateTicketStatus(ctx context.Context, arg CreateTicketStatusParams) (TicketStatus, error) {
	row := q.db.QueryRowContext(ctx, createTicketStatus,
		arg.Title,
		arg.Color,
		arg.Position,
		arg.IsClosed,
	)
	var i TicketStatus
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Color,
		&i.Position,
		&i.IsClosed,
	)
	return i, err
}

const deleteTicketStatus = `-- name: DeleteTicketStatus :exec
DELETE FROM ticket_statuses
WHERE id = $1
`

func (q *Queries) DeleteTicketStatus(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTicketStatus, id)
	return err
}

const getTicketStatus = `-- name: GetTicketStatus :one
SELECT id, title, color, position, is_closed FROM ticket_statuses
WHERE id = $1
`

func (q *Queries) GetTicketStatus(ctx context.Context, id int32) (TicketStatus, error) {
	row := q.db.QueryRowContext(ctx, getTicketStatus, id)
	var i TicketStatus
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Color,
		&i.Position,
		&i.IsClosed,
	)
	return i, err
}

const listTicketStatuses = `-- name: ListTicketStatuses :many
SELECT id, title, color, position, is_closed FROM ticket_statuses
ORDER BY position ASC
`

func (q *Queries) ListTicketStatuses(ctx context.Context) ([]TicketStatus, error) {
	rows, err := q.db.QueryContext(ctx, listTicketStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketStatus
	for rows.Next() {
		var i TicketStatus
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Color,
			&i.Position,
			&i.IsClosed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE ticket_statuses
SET title = $2,
    color = $3,
    is_closed = $4
WHERE id = $1
RETURNING id, title, color, position, is_closed
`

type UpdateTicketStatusParams struct {
	ID       int32
	Title    string
	Color    string
	IsClosed bool
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (TicketStatus, error) {
	row := q.db.QueryRowContext(ctx, updateTicketStatus,
		arg.ID,
		arg.Title,
		arg.Color,
		arg.IsClosed,
	)
	var i TicketStatus
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Color,
		&i.Position,
		&i.IsClosed,
	)
	return i, err
}

const upsertTicketStatusByPosition = `-- name: UpsertTicketStatusByPosition :one
INSERT INTO ticket_statuses (title, color, position, is_closed)
VALUES ($1, $2, $3, $4)
ON CONFLICT (position) DO UPDATE
    SET title = EXCLUDED.title,
        color = EXCLUDED.color,
        is_closed = EXCLUDED.is_closed
RETURNING id, title, color, position, is_closed
`

type UpsertTicketStatusByPositionParams struct {
	Title    string
	Color    string
	Position int32
	IsClosed bool
}

func (q *Queries) UpsertTicketStatusByPosition(ctx context.Context, arg UpsertTicketStatusByPositionParams) (TicketStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertTicketStatusByPosition,
		arg.Title,
		arg.Color,
		arg.Position,
		arg.IsClosed,
	)
	var i TicketStatus
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Color,
		&i.Position,
		&i.IsClosed,
	)
	return i, err
}
