// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_comments.sql

package db

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :one
INSERT INTO ticket_comments (ticket_id, author_id, parent_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, ticket_id, author_id, parent_id, body, created_at, updated_at, deleted
`

type CreateCommentParams struct {
	TicketID int64
	AuthorID int32
	ParentID sql.NullInt64
	Body     string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (TicketComment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.TicketID,
		arg.AuthorID,
		arg.ParentID,
		arg.Body,
	)
	var i TicketComment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, ticket_id, author_id, parent_id, body, created_at, updated_at, deleted FROM ticket_comments WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (TicketComment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i TicketComment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const listCommentsByTicket = `-- name: ListCommentsByTicket :many
SELECT id, ticket_id, author_id, parent_id, body, created_at, updated_at, deleted FROM ticket_comments
WHERE ticket_id = $1 AND deleted = FALSE
ORDER BY created_at ASC
LIMIT  $3::INTEGER
OFFSET $2::INTEGER
`

type ListCommentsByTicketParams struct {
	TicketID int64
	Off      int32
	Lim      int32
}

func (q *Queries) ListCommentsByTicket(ctx context.Context, arg ListCommentsByTicketParams) ([]TicketComment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByTicket, arg.TicketID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketComment
	for rows.Next() {
		var i TicketComment
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.AuthorID,
			&i.ParentID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE ticket_comments
SET deleted = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteComment, id)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE ticket_comments
SET body = $2, updated_at = NOW()
WHERE id = $1 AND deleted = FALSE
RETURNING id, ticket_id, author_id, parent_id, body, created_at, updated_at, deleted
`

type UpdateCommentParams struct {
	ID   int64
	Body string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (TicketComment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.ID, arg.Body)
	var i TicketComment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}
