// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createLDAPLogin = `-- name: CreateLDAPLogin :one
INSERT INTO ldap_login (id, distinguished_name, uid, sam_account_name, upn, object_guid, object_sid, ldap_server, base_dn)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, distinguished_name, uid, sam_account_name, upn, object_guid, object_sid, ldap_server, base_dn, last_synced_at
`

type CreateLDAPLoginParams struct {
	ID                int32
	DistinguishedName string
	Uid               sql.NullString
	SamAccountName    sql.NullString
	Upn               sql.NullString
	ObjectGuid        uuid.NullUUID
	ObjectSid         sql.NullString
	LdapServer        string
	BaseDn            string
}

func (q *Queries) CreateLDAPLogin(ctx context.Context, arg CreateLDAPLoginParams) (LdapLogin, error) {
	row := q.db.QueryRowContext(ctx, createLDAPLogin,
		arg.ID,
		arg.DistinguishedName,
		arg.Uid,
		arg.SamAccountName,
		arg.Upn,
		arg.ObjectGuid,
		arg.ObjectSid,
		arg.LdapServer,
		arg.BaseDn,
	)
	var i LdapLogin
	err := row.Scan(
		&i.ID,
		&i.DistinguishedName,
		&i.Uid,
		&i.SamAccountName,
		&i.Upn,
		&i.ObjectGuid,
		&i.ObjectSid,
		&i.LdapServer,
		&i.BaseDn,
		&i.LastSyncedAt,
	)
	return i, err
}

const createLocalLogin = `-- name: CreateLocalLogin :exec
INSERT INTO local_login (id, password_hash, must_change_pw)
VALUES ($1, $2, $3)
`

type CreateLocalLoginParams struct {
	ID           int32
	PasswordHash string
	MustChangePw bool
}

func (q *Queries) CreateLocalLogin(ctx context.Context, arg CreateLocalLoginParams) error {
	_, err := q.db.ExecContext(ctx, createLocalLogin, arg.ID, arg.PasswordHash, arg.MustChangePw)
	return err
}

const createMaintainerProfile = `-- name: CreateMaintainerProfile :one
INSERT INTO maintainer_profile (id, access_level, managed_scope)
VALUES ($1, $2, $3)
RETURNING id, access_level, managed_scope
`

type CreateMaintainerProfileParams struct {
	ID           int32
	AccessLevel  int16
	ManagedScope sql.NullString
}

func (q *Queries) CreateMaintainerProfile(ctx context.Context, arg CreateMaintainerProfileParams) (MaintainerProfile, error) {
	row := q.db.QueryRowContext(ctx, createMaintainerProfile, arg.ID, arg.AccessLevel, arg.ManagedScope)
	var i MaintainerProfile
	err := row.Scan(&i.ID, &i.AccessLevel, &i.ManagedScope)
	return i, err
}

const createStaffProfile = `-- name: CreateStaffProfile :one
INSERT INTO staff_profile (id, employee_id, department, job_title, is_teacher, employed_since)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, employee_id, department, job_title, is_teacher, employed_since
`

type CreateStaffProfileParams struct {
	ID            int32
	EmployeeID    string
	Department    sql.NullString
	JobTitle      sql.NullString
	IsTeacher     bool
	EmployedSince sql.NullTime
}

func (q *Queries) CreateStaffProfile(ctx context.Context, arg CreateStaffProfileParams) (StaffProfile, error) {
	row := q.db.QueryRowContext(ctx, createStaffProfile,
		arg.ID,
		arg.EmployeeID,
		arg.Department,
		arg.JobTitle,
		arg.IsTeacher,
		arg.EmployedSince,
	)
	var i StaffProfile
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Department,
		&i.JobTitle,
		&i.IsTeacher,
		&i.EmployedSince,
	)
	return i, err
}

const createStudentProfile = `-- name: CreateStudentProfile :one
INSERT INTO student_profile (id, student_id, enrolled_at, graduation_at, class_group)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, student_id, enrolled_at, graduation_at, class_group
`

type CreateStudentProfileParams struct {
	ID           int32
	StudentID    string
	EnrolledAt   time.Time
	GraduationAt sql.NullTime
	ClassGroup   sql.NullString
}

func (q *Queries) CreateStudentProfile(ctx context.Context, arg CreateStudentProfileParams) (StudentProfile, error) {
	row := q.db.QueryRowContext(ctx, createStudentProfile,
		arg.ID,
		arg.StudentID,
		arg.EnrolledAt,
		arg.GraduationAt,
		arg.ClassGroup,
	)
	var i StudentProfile
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.EnrolledAt,
		&i.GraduationAt,
		&i.ClassGroup,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, first_name, last_name, user_type, provider)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, first_name, last_name, user_type, provider, is_active, created_at, last_login_at
`

type CreateUserParams struct {
	Email     string
	FirstName sql.NullString
	LastName  sql.NullString
	UserType  UserType
	Provider  AuthProvider
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.UserType,
		arg.Provider,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deactivateUser, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getMaintainerByID = `-- name: GetMaintainerByID :one
SELECT
    u.id, u.email, u.first_name, u.last_name, u.provider, u.is_active, u.created_at, u.last_login_at,
    mp.access_level, mp.managed_scope
FROM users u
JOIN maintainer_profile mp ON mp.id = u.id
WHERE u.id = $1
`

type GetMaintainerByIDRow struct {
	ID           int32
	Email        string
	FirstName    sql.NullString
	LastName     sql.NullString
	Provider     AuthProvider
	IsActive     bool
	CreatedAt    time.Time
	LastLoginAt  sql.NullTime
	AccessLevel  int16
	ManagedScope sql.NullString
}

func (q *Queries) GetMaintainerByID(ctx context.Context, id int32) (GetMaintainerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMaintainerByID, id)
	var i GetMaintainerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.AccessLevel,
		&i.ManagedScope,
	)
	return i, err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT
    u.id, u.email, u.first_name, u.last_name, u.provider, u.is_active, u.created_at, u.last_login_at,
    sfp.employee_id, sfp.department, sfp.job_title, sfp.is_teacher, sfp.employed_since
FROM users u
JOIN staff_profile sfp ON sfp.id = u.id
WHERE u.id = $1
`

type GetStaffByIDRow struct {
	ID            int32
	Email         string
	FirstName     sql.NullString
	LastName      sql.NullString
	Provider      AuthProvider
	IsActive      bool
	CreatedAt     time.Time
	LastLoginAt   sql.NullTime
	EmployeeID    string
	Department    sql.NullString
	JobTitle      sql.NullString
	IsTeacher     bool
	EmployedSince sql.NullTime
}

func (q *Queries) GetStaffByID(ctx context.Context, id int32) (GetStaffByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getStaffByID, id)
	var i GetStaffByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.EmployeeID,
		&i.Department,
		&i.JobTitle,
		&i.IsTeacher,
		&i.EmployedSince,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT
    u.id, u.email, u.first_name, u.last_name, u.provider, u.is_active, u.created_at, u.last_login_at,
    sp.student_id, sp.enrolled_at, sp.graduation_at, sp.class_group
FROM users u
JOIN student_profile sp ON sp.id = u.id
WHERE u.id = $1
`

type GetStudentByIDRow struct {
	ID           int32
	Email        string
	FirstName    sql.NullString
	LastName     sql.NullString
	Provider     AuthProvider
	IsActive     bool
	CreatedAt    time.Time
	LastLoginAt  sql.NullTime
	StudentID    string
	EnrolledAt   time.Time
	GraduationAt sql.NullTime
	ClassGroup   sql.NullString
}

func (q *Queries) GetStudentByID(ctx context.Context, id int32) (GetStudentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getStudentByID, id)
	var i GetStudentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.StudentID,
		&i.EnrolledAt,
		&i.GraduationAt,
		&i.ClassGroup,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, user_type, provider, is_active, created_at, last_login_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, first_name, last_name, user_type, provider, is_active, created_at, last_login_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id FROM users WHERE email = $1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByEmail, email)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUserWithLDAPLogin = `-- name: GetUserWithLDAPLogin :one
SELECT
    u.id, u.email, u.first_name, u.last_name, u.user_type, u.provider, u.is_active, u.created_at, u.last_login_at,
    ldap.distinguished_name, ldap.uid, ldap.sam_account_name, ldap.upn,
    ldap.object_guid, ldap.object_sid, ldap.ldap_server, ldap.base_dn, ldap.last_synced_at
FROM users u
JOIN ldap_login ldap ON ldap.id = u.id
WHERE ldap.distinguished_name = $1 AND u.is_active = TRUE
`

type GetUserWithLDAPLoginRow struct {
	ID                int32
	Email             string
	FirstName         sql.NullString
	LastName          sql.NullString
	UserType          UserType
	Provider          AuthProvider
	IsActive          bool
	CreatedAt         time.Time
	LastLoginAt       sql.NullTime
	DistinguishedName string
	Uid               sql.NullString
	SamAccountName    sql.NullString
	Upn               sql.NullString
	ObjectGuid        uuid.NullUUID
	ObjectSid         sql.NullString
	LdapServer        string
	BaseDn            string
	LastSyncedAt      sql.NullTime
}

func (q *Queries) GetUserWithLDAPLogin(ctx context.Context, distinguishedName string) (GetUserWithLDAPLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserWithLDAPLogin, distinguishedName)
	var i GetUserWithLDAPLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.DistinguishedName,
		&i.Uid,
		&i.SamAccountName,
		&i.Upn,
		&i.ObjectGuid,
		&i.ObjectSid,
		&i.LdapServer,
		&i.BaseDn,
		&i.LastSyncedAt,
	)
	return i, err
}

const getUserWithLocalLogin = `-- name: GetUserWithLocalLogin :one
SELECT
    u.id, u.email, u.first_name, u.last_name, u.user_type, u.is_active, u.created_at, u.last_login_at,
    ll.password_hash, ll.must_change_pw, ll.pw_changed_at
FROM users u
JOIN local_login ll ON ll.id = u.id
WHERE u.email = $1 AND u.is_active = TRUE
`

type GetUserWithLocalLoginRow struct {
	ID           int32
	Email        string
	FirstName    sql.NullString
	LastName     sql.NullString
	UserType     UserType
	IsActive     bool
	CreatedAt    time.Time
	LastLoginAt  sql.NullTime
	PasswordHash string
	MustChangePw bool
	PwChangedAt  sql.NullTime
}

func (q *Queries) GetUserWithLocalLogin(ctx context.Context, email string) (GetUserWithLocalLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserWithLocalLogin, email)
	var i GetUserWithLocalLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
		&i.MustChangePw,
		&i.PwChangedAt,
	)
	return i, err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, email, first_name, last_name, user_type, provider, is_active, created_at, last_login_at
FROM users
WHERE is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.UserType,
			&i.Provider,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, first_name, last_name, user_type, provider, is_active, created_at, last_login_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.UserType,
			&i.Provider,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByType = `-- name: ListUsersByType :many
SELECT id, email, first_name, last_name, user_type, provider, is_active, created_at, last_login_at
FROM users
WHERE user_type = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUsersByType(ctx context.Context, userType UserType) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByType, userType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.UserType,
			&i.Provider,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncLDAPLogin = `-- name: SyncLDAPLogin :exec
UPDATE ldap_login
SET uid              = $2,
    sam_account_name = $3,
    upn              = $4,
    object_guid      = $5,
    object_sid       = $6,
    last_synced_at   = NOW()
WHERE id = $1
`

type SyncLDAPLoginParams struct {
	ID             int32
	Uid            sql.NullString
	SamAccountName sql.NullString
	Upn            sql.NullString
	ObjectGuid     uuid.NullUUID
	ObjectSid      sql.NullString
}

func (q *Queries) SyncLDAPLogin(ctx context.Context, arg SyncLDAPLoginParams) error {
	_, err := q.db.ExecContext(ctx, syncLDAPLogin,
		arg.ID,
		arg.Uid,
		arg.SamAccountName,
		arg.Upn,
		arg.ObjectGuid,
		arg.ObjectSid,
	)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, updateLastLogin, id)
	return err
}

const updateLocalLoginPassword = `-- name: UpdateLocalLoginPassword :exec
UPDATE local_login
SET password_hash  = $2,
    must_change_pw = FALSE,
    pw_changed_at  = NOW()
WHERE id = $1
`

type UpdateLocalLoginPasswordParams struct {
	ID           int32
	PasswordHash string
}

func (q *Queries) UpdateLocalLoginPassword(ctx context.Context, arg UpdateLocalLoginPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateLocalLoginPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateMaintainerProfile = `-- name: UpdateMaintainerProfile :exec
UPDATE maintainer_profile
SET access_level  = $2,
    managed_scope = $3
WHERE id = $1
`

type UpdateMaintainerProfileParams struct {
	ID           int32
	AccessLevel  int16
	ManagedScope sql.NullString
}

func (q *Queries) UpdateMaintainerProfile(ctx context.Context, arg UpdateMaintainerProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateMaintainerProfile, arg.ID, arg.AccessLevel, arg.ManagedScope)
	return err
}

const updateStaffProfile = `-- name: UpdateStaffProfile :exec
UPDATE staff_profile
SET department = $2,
    job_title  = $3,
    is_teacher = $4
WHERE id = $1
`

type UpdateStaffProfileParams struct {
	ID         int32
	Department sql.NullString
	JobTitle   sql.NullString
	IsTeacher  bool
}

func (q *Queries) UpdateStaffProfile(ctx context.Context, arg UpdateStaffProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateStaffProfile,
		arg.ID,
		arg.Department,
		arg.JobTitle,
		arg.IsTeacher,
	)
	return err
}

const updateStudentProfile = `-- name: UpdateStudentProfile :exec
UPDATE student_profile
SET graduation_at = $2,
    class_group   = $3
WHERE id = $1
`

type UpdateStudentProfileParams struct {
	ID           int32
	GraduationAt sql.NullTime
	ClassGroup   sql.NullString
}

func (q *Queries) UpdateStudentProfile(ctx context.Context, arg UpdateStudentProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateStudentProfile, arg.ID, arg.GraduationAt, arg.ClassGroup)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email      = $2,
    first_name = $3,
    last_name  = $4
WHERE id = $1
RETURNING id, email, first_name, last_name, user_type, provider, is_active, created_at, last_login_at
`

type UpdateUserParams struct {
	ID        int32
	Email     string
	FirstName sql.NullString
	LastName  sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.Provider,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
